import Head from 'next/head'
import type { NextPage } from 'next'
import Header from '@/components/Header'
Header

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Lucy Tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
        <Header/>


      {/* hero */}

      {/* about */}

      {/* experience */}

      {/* skills */}

      {/* projects */}

      {/* contact me */}

    </>
  )
}

export default Home